version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "00:00"
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "00:00"
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 3
